### ISSUE TITLE
Waben können nicht mehr angeklickt werden

### ISSUE THREAD

**Issue by VicKraft** [HakunaBanana/otw-bug-tracker#100]
Ich bin bei Alps auf den Pfeil zurück gegangen. Dadurch hat sich die  Ausstellerseite geschlossen, jedoch ist die Welt jetzt immer noch von wie bei einem Overlay verdunkelt. 
Die Welt dreht sich weiter, jedoch können keine Waben mehr angeklickt werden. Um weiter zu erkunden muss die Seite neu geladen werden. 
![Welt](https://user-images.githubusercontent.com/72913883/96440821-c93a1f80-1208-11eb-9c01-ffc13fc6d3fb.PNG)

**Comment by VicKraft** [comment]
Nochmal passiert bei Darco

**Comment by KNoellgen** [comment]
Vielleicht hilft der Hinweis, dass der Fehler bei mir nicht aufgetreten ist. Weder bei Alps, noch bei Darco.
