### ISSUE TITLE
MOWA Fehlermeldung Video

### ISSUE THREAD

**Issue by FrankyJones72** [HakunaBanana/otw-bug-tracker#101]
Video startet nicht - Fehlermeldung

**Comment by usluga** [comment]
Bei mir geht das Video auch nicht

**Comment by SchlSchleifnig** [comment]
To Do für @SchlSchleifnig   und @hannascholz

**Comment by hannascholz** [comment]
Kontakt mit MOWA (Herrn Schröder) neuer Link folgt

**Comment by hannascholz** [comment]
https://www.youtube.com/embed/J0bNNNCHyGE
Mit der Bitte Video auszutauschen @HakunaBanana

**Comment by HakunaBanana** [comment]
video aktualisiert
