### ISSUE TITLE
MOWA - Logo halb verdeckt 

### ISSUE THREAD

**Issue by VicKraft** [HakunaBanana/otw-bug-tracker#102]
Auf der englischen Seite wird das Logo größer dargestellt als auf der deutschen Seite und ist dadurch halb verdeckt. 
![Mowa_Logo](https://user-images.githubusercontent.com/72913883/96441525-ef13f400-1209-11eb-932f-b134385946e2.PNG)

**Comment by SchlSchleifnig** [comment]
@Gizmo2106  denke da muss Julian ran
