### ISSUE TITLE
Orthopädietechnik

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#104]
Beschreibung
Video funktioniert nicht

**Comment by SchlSchleifnig** [comment]
@hannascholz  bitte mal checken

**Comment by hannascholz** [comment]
Das ist der Verlag Orthopädietechnik - siehe LM Cloud, Video muss von Base Mesh gelöscht werden und Rest neu angeordnet werden @HakunaBanana @Gizmo2106
