### ISSUE TITLE
Acriba - Wabe leer und Logo verschoben 

### ISSUE THREAD

**Issue by VicKraft** [HakunaBanana/otw-bug-tracker#106]
Komplett keine Inhalte enthalten 
Logo größer als die Wabe und wahrscheinlich teilweise verdeckt 
![Acriba_Logo](https://user-images.githubusercontent.com/72913883/96441969-aad52380-120a-11eb-94c9-2604669efc29.PNG)

**Comment by SchlSchleifnig** [comment]
TO Do @Gizmo2106  und @HakunaBanana

**Comment by HakunaBanana** [comment]
@hannascholz @SchlSchleifnig das Logo was Acriba uns gesendet hat ist leider nicht 16:9. Da müssten wir nochmal nachfragen.

**Comment by hannascholz** [comment]
Acriba wurde angeschrieben

**Comment by hannascholz** [comment]
E-mail an @HakunaBanana @Gizmo2106
