### ISSUE TITLE
Medi GmbH

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#11]
Beschreibung
Englische Version Youtube Link geht nicht

**Comment by hannascholz** [comment]
@Gizmo2106 Hat das der Aussteller falsch eingegeben? Sprich: braucht man den Link nochmals? Oder könnt ihr den fehler beheben?

**Comment by Gizmo2106** [comment]
Das machen wir wenn das Upload Tool geschlossen ist

**Comment by HakunaBanana** [comment]
@hannascholz Kunde hat noch keine Youtube id hinterlegt. gilt für de/en. Der Rest ist vollständig

**Comment by hannascholz** [comment]
@HakunaBanana siehe LM Cloud - Kunde reicht Youtube links per E-mail nach
