### ISSUE TITLE
OTW Wabe - Inhalt 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#112]
BUGs / fehlend: 
- Logo im Kopf des Wabeneingangs
- Bild bei allg. Beschreibung engl. / dt. 
- Icon-Verlinkung Google Maps mit 404-Fehler 

Inhaltliche Anregungen: 
- Impressionen-Video von 2018 verlinken? https://www.youtube.com/watch?v=enrBq09TnYw&t=5s
- Download: aktuelles Logo / Logo für 2022

**Comment by KNoellgen** [comment]
Wäre es möglich die Wabe mit der dauerhaft eingeblendeten "halben" OTWconnect-Wabe zu verlinken? 
-> Per Click auf die dauerhaft eingeblendete Wabe würde man dann auf den befüllte gelangen.

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  den letzten KOmmentar finde ich als Idee sehr gut. Bitte so umsetzen.

@HakunaBanana  bitte auch Content noch einmal prüfen
