### ISSUE TITLE
Wabe inail

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#113]
Beschreibung
Inhalte fehlen

**Comment by HakunaBanana** [comment]
content gepflegt

**Comment by hannascholz** [comment]
Bitte Bild ändern in Company Description, siehe E-mail @HakunaBanana @Gizmo2106

**Comment by Gizmo2106** [comment]
Foto ist das selbe was schon drin war im Anhang der Mail

**Comment by Gizmo2106** [comment]
Trotzdem getauscht

**Comment by hannascholz** [comment]
ok super danke
