### ISSUE TITLE
Orliman

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#12]
Beschreibung
Noch keine Kunden Daten 
kein Deeplink

**Comment by hannascholz** [comment]
Aussteller angeschrieben am 14.10 HS

**Comment by hannascholz** [comment]
Bitte drei Fotos einfügen + Text, sowie Katalog als Pdf in Dowloaddateien integrieren. 
Hierzu ebenfalls E-mail @HakunaBanana @Gizmo2106 
![Fixquick 1280x720](https://user-images.githubusercontent.com/72912195/96990036-d61b8380-1526-11eb-97c1-7bfad9eba3e6.jpg)
![Maternity 1280x720](https://user-images.githubusercontent.com/72912195/96990040-d74cb080-1526-11eb-8739-db821e18f554.jpg)


![Dorsotech 1280x720](https://user-images.githubusercontent.com/72912195/96990024-d3b92980-1526-11eb-8d55-c936e3e64364.jpg)
[ENVIO.docx](https://github.com/HakunaBanana/otw-bug-tracker/files/5428740/ENVIO.docx)

https://drive.google.com/drive/folders/1hjfcZcjdwesIuvhEWaDjcOOf1w-n0_Go?usp=sharing
