### ISSUE TITLE
Wabe orthosoft

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#123]
Beschreibung
keine Inhalte

**Comment by SchlSchleifnig** [comment]
Content wurde nur einsprachig gepflegt. vorhandener Content muss noch in die jeweilig andere Sprache kopiert werden.
To Do für BM @HakunaBanana

**Comment by Gizmo2106** [comment]
orthosoft ???

**Comment by Gizmo2106** [comment]
MMO Michael Martin
