### ISSUE TITLE
Ansicht in Google Chrome

### ISSUE THREAD

**Issue by SBeckerLE1** [HakunaBanana/otw-bug-tracker#127]
Bei 2 von 4 Kollegen funktioniert die Ansicht in Google Chrome nicht. Nur die untere Hälfte der Wabenwelt wird angezeigt.
![Wabenwelt in Chrome](https://user-images.githubusercontent.com/72921516/96451219-892e6900-1217-11eb-89c4-cdce59025ef9.PNG)

**Comment by HakunaBanana** [comment]
@SchlSchleifnig Ich entwickle quasi ausschliesslich mit Chrome, das überrascht mich. Sind vllt Plugins installiert, die das Laden von Javascript verhindern? Welche Google Chrome Version ist das? Eine weitere Möglichkeit wäre eine zu alte Chrome Version.

Unitys Webgl und somit auch zwangsweise wir, unterstützen die größten Browser in den angebenen Versionen:
![image](https://user-images.githubusercontent.com/63208696/96521069-b3f8db80-1270-11eb-9e71-92557673cb00.png)
Kleinere Browser wie zB Netscape funktioneren zwar auch glaube ich, werden aber nciht offiziell unterstützt

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  die nun hochgeladenen Version der Wabenwelt läuft jetzt auch ohne Probleme im Chrome - habe es gerade getestet.
Ich bitte noch einmal bei der Verfasserin des Issues um einen erneuten Test

**Comment by SchlSchleifnig** [comment]
Wurde auf drei Rechnern getestet. Funktioniert
