### ISSUE TITLE
ständige Rotation der Wabenwelt

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#129]
Beschreibung
Ich finde die ständige Rotation der Wabenwelt irritierend. Müsste vielleicht langsamer sein, damit dies nicht so im Blickpunkt ist.

**Comment by lnoebel** [comment]
Sehen wir auch so. Ohne die Drehung war es benutzerfreundlicher und das Usererlebnis größer, da sich der Besucher selbst durch die Welt bewegen konnte. Zudem irritiert die Rotation, wenn man in einer Wabe drin ist und wieder rauskommt, da man sich nun neu orientieren muss.

**Comment by SchlSchleifnig** [comment]
wird gestrichen @HakunaBanana
