### ISSUE TITLE
Wabe OTWorld.connect 

### ISSUE THREAD

**Issue by lnoebel** [HakunaBanana/otw-bug-tracker#131]
Die Bilder in der Produktwelt ändern sich mit Anpassen des Seitenverhältnisses - ziehe ich das Browserfenster größer wird es verzerrt dargestellt, ziehe ich es kleiner, wird das Bild schmaler.

**Comment by SBeckerLE1** [comment]
In der deutschen Wabe funktioniert der Link zur Website nicht. Bitte zu https://www.ot-world.com/ verlinken. 
Ich glaub ich hatte keinen Link für Google Maps angelegt. Könnte der noch entfernt werden? Sonst wäre der glaube ich so?

https://www.google.com/maps/place/Leipziger+Messe+GmbH/@51.3946935,12.3960718,17z/data=!3m1!4b1!4m5!3m4!1s0x47a6578f15218505:0xb11e11a3e5f976ae!8m2!3d51.3946935!4d12.3982605?hl=de-DE
