### ISSUE TITLE
ORTHOSCOOT Videoaustausch

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#133]
Film (kommt per Mail) bitte mit Platzhalterdatei im Downloadbereich tauschen (Platzhalter ist auf der zweiten Stelle im deutschen Downloadbereich)

>>in der Deutschen Fassung im Download-Bereich an 2ter Stelle (!)
>> anstatt Platzhalterdatei namens "ORTHOSCOOT_Happiness_Trailer"
>> Die englische Seite bleibt unverändert.

gemäß Email vom 20.10.

**Comment by hannascholz** [comment]
@HakunaBanana @Gizmo2106 weiterhin To-Do Base Mesh

**Comment by HakunaBanana** [comment]
das video wurde aktualisiert

**Comment by hannascholz** [comment]
@HakunaBanana kein Video in ORTHOSCOOT Wabe!

**Comment by hannascholz** [comment]
@HakunaBanana wurde Video aktualisiert? E-mail zu Logo gesendet

**Comment by hannascholz** [comment]
Orthoscoot hat angerufen, Video im Downloadbereich wurde anscheinend nicht gewechselt. Bitte nochmal checken. So bald mir E-mail vorliegt leite ich diese weiter @HakunaBanana

**Comment by HakunaBanana** [comment]
@hannascholz ich habe das Video grade ausgetauscht
