### ISSUE TITLE
ISPO

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#135]
Beschreibung
Falsches Logo bitte 16 zu 9 und freigestellt 
Youtube Link ist auf Privat gestellt 
@SchlSchleifnig @hannascholz

**Comment by hannascholz** [comment]
@Gizmo2106 @HakunaBanana siehe hierzu meine E-mail an Benny am 19.10 (12.49 Uhr) Logo und Video Link liegen euch vor. Lass mich wissen falls es hier weitere TO-Do´s für uns gibt.
