### ISSUE TITLE
Bauerfeind: russiches YouTube-Video

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#137]
Bei Bauerfeind ist ein russisches YouTube Video hinterlegt - sowohl bei DE als auch ENG

Ist ein Platzhalter. Originalvideos werden am 22.10. nachgereicht - siehe LM Cloud Liste und Mail @HakunaBanana @Gizmo2106

**Comment by hannascholz** [comment]
D. Klein: 4r4PfWWPPMo

Prof. Sell: Wz43-_dSHhs

B. Beckmann: Ydo-z8Yum_0

T. Arlt/T. Wendl: li0YRdCvWBk


[Einbindung YouTube-Videos_Bauerfeind AG_Inkl. Verteilung Videos.pdf](https://github.com/HakunaBanana/otw-bug-tracker/files/5421547/Einbindung.YouTube-Videos_Bauerfeind.AG_Inkl.Verteilung.Videos.pdf)
@HakunaBanana @Gizmo2106  siehe hierzu auch E-mail
