### ISSUE TITLE
Kamerafahrt auf Welt zu

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#138]
Falls Kapazitäten übrig: Prüfung einer Kamerafahrt auf die Welt zu - bevor man in der Welt startet

**Comment by HakunaBanana** [comment]
Dieses Feature bringt eine Neuberechnung der kompletten Sphäremit bei jedem Schritt den man mit der Kamera tut und ist performance technisch eine Katastrophe. Beim rotieren in der MItte der Sphäre tritt dieses Phänomen nicht auf, da keine Neuberechnung von zB Sonneneinstrahlung etc. durchgeführt wird(nur einmal am Anfang)
