### ISSUE TITLE
PRIO: Datenschutz Pop Up individualisieren

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#141]
Es soll eine erkennbare Verbindung zwischen dem Datenschutz Pop Up und dem gerade besuchten Aussteller geben

**Comment by SchlSchleifnig** [comment]
Dazu bitte auch den aktuell roten Ablehn-Button farblich neutral gestalten. Weitere Infos per Mail

**Comment by HakunaBanana** [comment]
umgesetzt
