### ISSUE TITLE
Fehlermeldung 504 Gatweway Time-out

### ISSUE THREAD

**Issue by SBeckerLE1** [HakunaBanana/otw-bug-tracker#142]
Ich bin in eine neue Wabe gegangen und war nicht lang inaktiv aber bekam trotzdem eine Fehlermeldung, scheinbar wegen zulanger Inaktivität?

![grafik](https://user-images.githubusercontent.com/72921516/96694026-358f5d00-1388-11eb-9403-95989b26b265.png)

**Comment by HakunaBanana** [comment]
siehe #139
