### ISSUE TITLE
Downloadfiles teilweise schlecht lesbar 

### ISSUE THREAD

**Issue by mandyport** [HakunaBanana/otw-bug-tracker#144]
Downloads u.a. bei Blatchford und Opta Data schlecht lesbar aufgrund des dunkeln Hintergrundes 
Vorschlag: Kasten genauso hell darstellen wie die Visitenkarte 

Zudem finde ich es etwas irritierend, dass die Downloaddatei "verschwommen" dargestellt wird, wenn man mit der Maus drüberfährt, das heiß nicht mehr lesbar ist. Besser wäre, wenn der Dateiname vergrößert dargestellt werden würde, das animiert eher zum anklicken und herunterladen.

**Comment by HakunaBanana** [comment]
gefixt
