### ISSUE TITLE
Thuasne - 25 Dateien

### ISSUE THREAD

**Issue by hannascholz** [HakunaBanana/otw-bug-tracker#145]
@HakunaBanana @Gizmo2106 bitte kontrollieren ob 25 Dateien hinterlegt sind, nicht in Wabenwelt erkennbar

**Comment by HakunaBanana** [comment]
@hannascholz Thuasne hat sowohl in der de, als auch der en Fassung jeweils 7 Dateien hochgeladen.(aber platz für 25)
Viele Grüße

**Comment by hannascholz** [comment]
ok danke für die Info und gegenchecken
