### ISSUE TITLE
Logo Claim bei vielen Waben nicht lesbar 

### ISSUE THREAD

**Issue by mandyport** [HakunaBanana/otw-bug-tracker#146]
Vor allem der Claim im Logo ist bei vielen Ausstellern nicht lesbar, 
u.a. bei folgenden Firmen: 
INAIL
BUFA
OTWorld 
GhiWell
Streifeneder
Spentys
con.fair.med
Blatchford
ORTHOSCOOT - hier ist das SCOOT im Namen immer noch nicht gut lesbar 

Kann man hier noch was optimieren? Der Claim ist sehr wichtig für die Markenwiedererkennung.

**Comment by base-mesh** [comment]
für den Claim könnte man ein Bold Schriftart verwenden allerding könnte dies von dem CI des Kunden abweichen . Am besten wäre es in der Wabenwelt auf den Claim zu verzichten, der Claim wird ja weiterhin in der zweiten Ebene sichtbar sein.

Ein andere Möglichkeit wäre es mit der Kamera mehr rein zu Zoomen. dadurch erzeugen wir aber einen kleineren Bildausschnitt der weniger Kunden aufeinmal darstellt.

MIt freundlichen Grüßen 

Julian

**Comment by HakunaBanana** [comment]
Wir haben den anderen Weg gewählt und vergrößern die Waben an sich beim drüber hovern. Ein reinzoomen ist technisch nur sehr schwer umsetzbar und würde das Gesamt-Erscheinungsbild kaputt machen.
