### ISSUE TITLE
Medi auf BG Etem verlinkt oder Falsches Logo

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#15]
Beschreibung

**Comment by KNoellgen** [comment]
zusätzliche Hinweise 

**Link Videokonferenz funktioniert nicht (401-Fehler)**

Unauthorized

This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

**Verlinkung Socical Medie funktionieren nicht**

Insta und FB mit 404 Fehler - Page not found

**Comment by HakunaBanana** [comment]
Das konnte ich nicht verifizieren. Bei mir führt ein Klick auf die jeweilige Wabe zum richtigen Partner.

id: bg-etem
Kunde  Bg-Etem: hat ein unvollständiges Profil(je Sprache entweder leer lassen, oder alles ausfüllen)

**Comment by HakunaBanana** [comment]
Um auf Nummer sicher zu gehen wird die falsche Wabe Problematik hier weitergeführt: #87

**Comment by SchlSchleifnig** [comment]
ich habe sowohl Social Media als auch Videokonferenzlink getestet. Auch bei mir läuft alles.
Links fürehn ebenfalls zum richtigen Partner
