### ISSUE TITLE
erneute Anmeldung nicht möglich

### ISSUE THREAD

**Issue by bmuthmann** [HakunaBanana/otw-bug-tracker#151]
Beschreibung
Nachdem ich nach Abschluss meines Testes (ohne weitere Auffälliggkeiten - außer der bereits von den Kollegen genannten Punkten) ein paar Minuten nichts mehr bewegt hatte, wurde ich automatisch ausgeloggt und konnte mich allerdings nicht erneut einloggen. Trotz mehrfach richtiger Eingabe und auch Nutzung der Assistenzfunktion "Gespeicherte Zugangsdaten anzeigen" und hieraus kopieren kam immer wieder die Meldung "Ungültiger Benutzername oder Passwort". Auch der Versuch, sich als neuer Benutzer ein weiteres Mal zu registrieren, schlug fehl. Hierbei wurde dann richtigerweise angezeigt, dass dieser Zugang bereits existiert. Auch bei völlig neuem Aufruf des Links zur Wabenwelt, den uns Lisa gesendet hatte, war ein erneutes Einloggen nicht möglich.

**Comment by HakunaBanana** [comment]
Diese Website liegt leider ausserhalb unseres Einflusses, da sollte vllt das Keycloak team mal nach schauen. @hannascholz @SchlSchleifnig

**Comment by hannascholz** [comment]
im Termin 22.10 mit Carmen Rogge besprochen, Weiterleitung an Matthias Folk / Keycloak team über Jira
