### ISSUE TITLE
Aether biomedical - Videokonferenz

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#153]
Videokonferenz wird über Google Meets gestartet.
Teilnahme leider nur möglich, wenn ich ein Google Konto angebe.

Wahrscheinlich ist die Meetingeinstellung auf privat oder ähnlich.

@hannascholz  könntest du bitte Aussteller darauf hinweisen

**Comment by hannascholz** [comment]
Aussteller informiert, neuer Link zum Kommunikationstool folgt morgen bis Mittags

**Comment by hannascholz** [comment]
Bitte verwendet diesen Zoom Link @HakunaBanana @Gizmo2106 

https://us04web.zoom.us/j/8690309564?pwd=dDRxWXZLRVpiWEl3eERpNjZONUVaUT09

**Comment by Gizmo2106** [comment]
Wurde getaucht

Am Mi., 21. Okt. 2020 um 17:36 Uhr schrieb hannascholz <
notifications@github.com>:
