### ISSUE TITLE
Metiz - Videokonferenz

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#154]
Es wird Skype genutzt. Man braucht aber unter den aktuellen Einstellungen ein Konto bei Skype, um teilzunehmen.
Zusätzlich wird Skype als Browserapplikation nur im Chrome unterstützt. Nicht aber im Firefox.

@hannascholz  bitte Hinweis an Metiz bzw. AV Moskau

**Comment by hannascholz** [comment]
Metiz angeschrieben, AP erst Freitag wieder im Haus
