### ISSUE TITLE
Optadat - Videokonferenztool

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#155]
Link führt ins leere.

@HakunaBanana  bitte melden, woran es liegt.
@hannascholz  übernimmt dann Kundenkontakt

**Comment by Gizmo2106** [comment]
Kein Videotool gesetzt weder im deutsch noch in english

**Comment by hannascholz** [comment]
https://www.gotomeet.me/MarcUlrichson
@HakunaBanana @Gizmo2106  bitte einfügen
