### ISSUE TITLE
Usability - Laden der Inhalte über WLAN-Verbindung verzögert

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#156]
Beschreibung
Über eine WLAN-Verbindung  laden sowohl die Waben in der Übersicht als auch die Bilder in den Produktwelten sehr langsam.

Möglicherweise kann man dies optimieren, wenn die Bildern in kleineren Dateigrößen hochgeladen werden?

**Comment by HakunaBanana** [comment]
Die maximale Dateigröße war 10Mb, die tatsächliche Größe wird vom Kunden bestimmt @hannascholz @SchlSchleifnig

**Comment by hannascholz** [comment]
@HakunaBanana wir dachten die Dateigröße wird automatisch durch das Uploadtool vorgegeben und kann somit vom Kunde nicht überschritten werden?

**Comment by HakunaBanana** [comment]
@hannascholz wird es auch, die maximale Dateigröße betrug 10Mb, alles darunter ist möglich.
Viele Grüße
