### ISSUE TITLE
Usability - Maus ändert die Darstellung nicht beim Mouseover über die Waben

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#157]
Wenn man mit der Maus über die Waben fährt, dann ändert sich die Darstellung der Maus nicht in das "Hand-Symbol", sodass nicht gleich deutlich ist, ob man die Wabe anklicken kann oder nicht.

**Comment by HakunaBanana** [comment]
duplikat
