### ISSUE TITLE
Registrierung - Anrede und Land ohne Vorauswahl

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#158]
Beschreibung
Während des Registrierungsprozesses muss man u.a. seine Anrede und das Land angeben.
Beide Felder sind nicht mit einem Dropdown-Menü hinterlegt.

Das könnte für die spätere Erfassung der Daten Schwierigkeiten mit sich bringen, z.B. durch Tippfehler.

**Comment by HakunaBanana** [comment]
Diese Website liegt leider ausserhalb der wabenwelt und kann somit nicht von uns beinflusst werden @hannascholz @SchlSchleifnig

**Comment by hannascholz** [comment]
To-Do FAIRNET / Absprache mit Leipziger Messe
