### ISSUE TITLE
Metiz

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#16]
Beschreibung
Youtubelink falsch

**Comment by Gizmo2106** [comment]
Fehlen noch Daten

**Comment by hannascholz** [comment]
@Gizmo2106 welche Daten fehlen? Youtubelink deustsch / englisch oder beide falsch?

**Comment by KNoellgen** [comment]
> 
> 
> @Gizmo2106 welche Daten fehlen? Youtubelink deustsch / englisch oder beide falsch?

Dt.: 
- allg. Beschreibung
- Video
- Produktbeschreibungen plus Bilder 

Engl.:
- Video

- Verlinkungen in den Icons fehlen alle
- kein Download
- keine Kontaktdaten

**Comment by hannascholz** [comment]
@SchlSchleifnig  Laut LM Cloud, werden 15 Bilder + 15 Bildtexte benötigt? Es sind aber nur 12 hinterlegt/ befüllt ? Hast du hierzu eine andere Info? Ansonsten RS mit Base Mesh und ich nehme nochmal Kontakt mit Metiz auf

**Comment by SchlSchleifnig** [comment]
@hannascholz  ich habe auch keine weiterführenden Infos. 
Metiz läuft ja immer über die AV Moskau - evtl weiß er etwas? 
Um uns keine Baustelle zu eröffnen, könnten wir es entweder so lassen oder wir schicken noch einmal einen Screenshot zur Freigabe zum Aussteller?

**Comment by hannascholz** [comment]
@SchlSchleifnig ich kläre das mit der AV, hatte schon mehrfach kontakt mit ihm. Dann haben wir uns abgesichert
