### ISSUE TITLE
Fehler DZH - Die Unterseite zur Produktwelt funktioniert nicht

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#165]
Beschreibung
Bei der Firma DZH werden die Inhalte innerhalb der Produktwelt nicht angezeigt
![Fehler_DZH](https://user-images.githubusercontent.com/73229777/96728674-a2b8e780-13b4-11eb-80c1-144a96de685a.JPG)

**Comment by hannascholz** [comment]
@HakunaBanana mit Produktwelt bei allen 6 Spezialwaben raus löschen. @MGoetzLM ist spezialwabe und hat somit keine Produktwelt.
