### ISSUE TITLE
Fehler Ortho SOLID - Google Maps Button funktioniert nicht 

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#169]
Beschreibung

**Comment by hannascholz** [comment]
@HakunaBanana Wenn google maps butten leer, Button löschen @MGoetzLM wer ist Ortho solid?

**Comment by MGoetzLM** [comment]
@hannascholz 
Die Wabe liegt zwischen METIZ, DARCO und CAROLI und heißt OrthoSOLID.
Anhand der E-Mail-Adressen in der Visitenkarte könnte die Firma Orthobroker sein.

**Comment by hannascholz** [comment]
Orthobroker, super danke! 
Aussteller ist angeschrieben
