### ISSUE TITLE
Suche - Suchoptimierung durch Algorithmen

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#171]
Beschreibung
Gerade bei den unterschiedlichen Schreibweisen (je nach Sprache), z.B. Ortho und Orto, würde ich eine intelligente Suche als sinnvoll erachten, wenn man nicht nach Produktgruppen filtern kann, um die Suche einzugrenzen.

**Comment by HakunaBanana** [comment]
Es ist soeben eine Branchenfilterung möglich geworden
