### ISSUE TITLE
Support - Gibt es einen Troublecounter o.ä.?

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#173]
Beschreibung
Gibt es außerhalb der Wabenwelt einen Troublecounter oder ähnliches, über welchen Teilnehmer, Referenten und Aussteller das Team bei Problemen kontaktieren können?
Ansonsten würde es ich eventuell anbieten, innerhalb der OTWorld Wabe das Konferenzmanagementtool einzubinden und jemanden vom Team dort mit Video zur Verfügung zu stellen für Fragen und Probleme.

**Comment by SchlSchleifnig** [comment]
Es gibt eine Service-Team, was telefonisch und per Mail den Besuchern, Rednern, Ausstellern zur Verfügung steht. Innerhalb der Wabenwelt ist in der OTW Wabe eine der Servicenummern abgebildet.
