### ISSUE TITLE
Orliman-Wabe: Videokonferenz

### ISSUE THREAD

**Issue by MarieGerken** [HakunaBanana/otw-bug-tracker#174]
Beschreibung
Bei der Videoknoferenz mit Team wird nicht die Nutzung im Browser angeboten -bei anderen Ausstellern schon. Liegt dies evtl. an Einstellung, die der Ausstelller beeinflussen kann?

**Comment by hannascholz** [comment]
Info an Kunde erfolgt

**Comment by HakunaBanana** [comment]
![image](https://user-images.githubusercontent.com/63208696/97106960-08fb7e00-16c5-11eb-8a3f-0377df628e00.png)
Kunde bietet jetzt Browser Benutzung mit an.
