### ISSUE TITLE
Optica-Wage: Video im Hauptmenü

### ISSUE THREAD

**Issue by MarieGerken** [HakunaBanana/otw-bug-tracker#175]
Beschreibung
Video ist ohne Ton. Scheint aber eigentlich Ton zu brauchen.

**Comment by hannascholz** [comment]
Aussteller angeschrieben, telefonisch nicht erreicht

**Comment by hannascholz** [comment]
Videolink kommt morgen vormittag, Freitag 23.10

**Comment by hannascholz** [comment]
Videolink wurde selbst vom Kunde eingefügt, bitte noch E-mail adresse in Visitenkarte austauschen @HakunaBanana @Gizmo2106 

omnia-branchensoftware@optica.de

**Comment by Gizmo2106** [comment]
wurde getauscht sowie Video in der englischen Version
