### ISSUE TITLE
Usability - Fehlermeldung bei Verlassen der Seite über "Browser-Buttons"

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#176]
Wenn man den "Zurück-Pfeil" des Browsers (Chrome) nutzt, hängt sich die Seite auf und bringt folgende Fehlermeldung (Anhang):
Durch nochmaliges Drücken des "Zurück-Pfeils" gelangt man wieder in die Wabenwelt
![Fehler_Zurückgehen_ueber_Browser](https://user-images.githubusercontent.com/73229777/96732929-2aa0f080-13b9-11eb-81ae-5ebd8b6d26fb.JPG)

**Comment by HakunaBanana** [comment]
Dies liegt leider nicht in unserem Zuständigkeitsbereich. Diese Funktion wird vom Browser übernommen
