### ISSUE TITLE
Fehler - Wabe BionIT Labs

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#178]
Beschreibung
1. Zeile von jedem Absatz des Beschreibungstextes ist eingerückt.
![Fehler_BionIT](https://user-images.githubusercontent.com/73229777/96733853-3345f680-13ba-11eb-904e-6a1f53dd5ed5.JPG)

**Comment by hannascholz** [comment]
@Gizmo2106 @HakunaBanana könnt ihr bitte die Leerzeichen raus nehmen ? Danke
