### ISSUE TITLE
Streifenender

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#18]
Beschreibung
Download falsche Anzeige Zeilenumbruch kein freigestelltes Logo
Info Text Scroll Funktion auch nur rechts

**Comment by hannascholz** [comment]
Aussteller zu Logo angeschrieben am 14.10 HS

**Comment by HakunaBanana** [comment]
Download bug ist gefixt. scrollen wird unter #88 behandelt
