### ISSUE TITLE
Medi Hauptseite

### ISSUE THREAD

**Issue by MarieGerken** [HakunaBanana/otw-bug-tracker#188]
Beschreibung
Bei Switch auf Englisch kommt anderer Text, der nicht willkommen heitß und etwas ins Wasser schmeißt.
Kein Video vorhanden? Videokonferenztool wird nicht bespielt. Wirkt wenig ausdrucksstark, obwohl Sponsor.

**Comment by hannascholz** [comment]
Bitte Videos einfügen, sowie Fotos löschen/ tauschen siehe hierzu WordDokument im anhang und E-mail @HakunaBanana @Gizmo2106 
![Uploading ONBA-1920x1080-PHL-mediven-FS-OT-World-GER-INT-2020-10-06.png…]()

**Comment by hannascholz** [comment]
@HakunaBanana @Gizmo2106 Bitte daten ändern / tauschen, hierzu auch per E-mail.
![ONBA-1920x1080-PHL-OT-World-online-platform-banner-GER-INT-2020-10-08](https://user-images.githubusercontent.com/72912195/97020734-3673ea80-1552-11eb-81bb-076b06e79cd9.png)
[Uploading Videos + Änderungen.docx…]()
