### ISSUE TITLE
BIV-Wabe

### ISSUE THREAD

**Issue by MarieGerken** [HakunaBanana/otw-bug-tracker#189]
Beschreibung
Kein Englischer Text hinterlegt

**Comment by MarieGerken** [comment]
Produkt Menu funktioniert nicht.

**Comment by HakunaBanana** [comment]
Welcher Kunde ist hier gemeint?

**Comment by MarieGerken** [comment]
Die Wabe vom BIV (Bundesinnungsverband Orthopädie-Technik)

**Comment by hannascholz** [comment]
"Produkt Menu funktioniert nicht. " ?? welche daten fehlen hier?? @HakunaBanana

**Comment by HakunaBanana** [comment]
@hannascholz der Kunde hat keine Produkte eingetragen.

**Comment by hannascholz** [comment]
ok dann ist das so :) kein weitere To-Do erforderlich
