### ISSUE TITLE
Spentys: Videokonferenz

### ISSUE THREAD

**Issue by MarieGerken** [HakunaBanana/otw-bug-tracker#193]
Beschreibung
Bei klicken auf das Personen-Icon wird man zur Terminvereinbarung für eine Videkonferenz über Microsoft-Teams geleitet. Link habe ich automatisiert erhatlen. Hat allerdings nicht funktioniert. Chrome sagt, dass die Seite nicht funktioniert.

**Comment by MarieGerken** [comment]
Unternehmen hat mir per E-Mail nochmal Link geschickt. Danach konnten wir problmelos (allerdings nur über  Chrome)Videokonferenz halten.

**Comment by HakunaBanana** [comment]
Die weiterleitung auf die Seite funktioniert.
