### ISSUE TITLE
DARCO

### ISSUE THREAD

**Issue by hannascholz** [HakunaBanana/otw-bug-tracker#194]
Flyer austauschen in Dokumente, Anhang folgt per E-mail @HakunaBanana @Gizmo2106

**Comment by hannascholz** [comment]
@HakunaBanana @Gizmo2106 
Sorry, Darco ist super pingelig. Könnt ihr bitte die 1 im Dokumenten Namen bei der Downloaddatei entfernen? Danke 

"könnten Sie nur bitte den Flyer ersetzen, sodass hier nicht die 1 in den Klammern steht?"

**Comment by HakunaBanana** [comment]
@hannascholz done
