### ISSUE TITLE
Ausstellerworkshops auch in einzelnen Waben der involvierten Aussteller präsentieren

### ISSUE THREAD

**Issue by MarieGerken** [HakunaBanana/otw-bug-tracker#195]
Beschreibung
Evtl. kann das PT den Ausstellern den Anreiz geben, Workshops in Ihrer Wabe aufzunehmen. War bei Spentys nicht der Fall, als ich mit Ihnen über Video gesprochen habe, fand ich zufällig raus, dass sie Workshop machen. Ich fänd es aber zur Orientierung gut, wenn sie es mit in Beschreibung aufnehmen oder bei mehreren Workshops eine Grafik gestalten, in der sie darauf hinweisen.

**Comment by SchlSchleifnig** [comment]
Die Aussteller hatten die Option, einen "Live Ticker" zu buchen, um genau dort ihre Live Sessions anzuzeigen.
