### ISSUE TITLE
Verlag Orthopädie Technik

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#20]
Beschreibung
Deeplinks steht verband anstatt Verlag
youtube links falsch

**Comment by hannascholz** [comment]
@Gizmo2106 : Bitte Hinweis welcher Aussteller exakt, da hier mehrere

**Comment by Gizmo2106** [comment]
Alles klar kümmere mich drum

**Comment by HakunaBanana** [comment]
Es handelt sich um Kunden "Verlag Bundesinnungsverband für Orthopädie-Technik/ Verlag Orthopädie Technik"
mit id: verband-orthopaedie

Kunde hat noch keine Youtube id hinterlegt

**Comment by hannascholz** [comment]
@HakunaBanana siehe Excelliste, Youtube Video sowie Kommunikationslink/ wabe werden von Base Mesh bis 13.10 entfernt

**Comment by hannascholz** [comment]
Nach wie vor TO-Do Base Mesh @HakunaBanana @Gizmo2106
