### ISSUE TITLE
Abmelden aus dem System

### ISSUE THREAD

**Issue by MGoetzLM** [HakunaBanana/otw-bug-tracker#200]
Beschreibung
Man muss sich zu Beginn anmelden/registrieren, um in die Wabenwelt zu gelangen, aber man kann sich nicht wieder ausloggen.

Für Nutzer eines PCs, der von verschiedenen Leuten benutzt wird, ist das ein Sicherheitsrisiko.

**Comment by HakunaBanana** [comment]
Der Login ist soweit ich weiss 30 Minuten gültig. Danach muss man sich neu einloggen.

**Comment by SchlSchleifnig** [comment]
Dies wird durch die dann aktivierte Landing Page der LM gesteuert. Ich kann man sich auch abmelden.
