### ISSUE TITLE
neue Lobby-Seite hinter dem OTW-Banner verlinken

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#203]
Wenn man aus der Wabenwelt zurück zu den anderen Programmmöglichkeiten kommen möchte, klickt man auf das OTW-Banner.
Aktuell kommt man noch auf die Landingpage.

Für die Live-Veranstaltung gibt es eine spezielle Lobby. 
Für den Besucher ist es sinnvoller, dorthin zu gelanden.

https://connect.ot-world.com/de/lobby

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  gemäß meiner Mail gerade

**Comment by HakunaBanana** [comment]
@SchlSchleifnig Die Lobbyseite sieht echt schick aus. Wird erledigt

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  super, danke.

Könntest du noch umsetzen, dass dies im gleichen Tab passiert und sich hier nicht ein neuer Tab öffnet?

**Comment by HakunaBanana** [comment]
@SchlSchleifnig das ist leider nicht so ohne weiteres möglich. Die URL https://connect.ot-world.com/de/lobby schickt einen speziellen Header mit (X-Frame-Options: deny) der verhindert das man das über ein iframe und somit als overlay über die app, öffnet. Ich werde den Link im Banner ersetzen.

**Comment by HakunaBanana** [comment]
die lobby Seite ist jetzt live im System. Hier wird immer noch ein neuer Tab geöffnet. @SchlSchleifnig Ich kann die Seite auch im selben Tab öffnen, das würde aber ein neues Laden der App mit sich bringen, wenn man wieder zurück will. Da bin ich kein Fan von, wie seht ihr das?

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  ich habe es kurz mit @hannascholz diskutiert. Wir wären beide dafür, dass wir im gleichen Tab bleiben, wenn man von der Wabenwelt zurück zur Lobby geht.

Man entscheidet sich ja aktiv, vom Ausstellungsbereich zurück zu den anderen Möglichkeiten der OTW zu wechseln. Dann passt es vielleicht besser, wenn man im gleichen Tab/Fesnter bleibt.

Damit müsste es für unsere Analytics auch besser nachvollziehbar sein, wie lange der Besucher auch wirklich in der Wabe geblieben ist....

Also gerne im gleichen Tab... aber nur wenn es problemlos machbar ist. ;)
