### ISSUE TITLE
Orthobroker - zwei Mal in Suchfunktion

### ISSUE THREAD

**Issue by hannascholz** [HakunaBanana/otw-bug-tracker#206]
@HakunaBanana 
Orthobroker taucht zweimal in der Scrollbar/ Suchfunktion auf, einmal mit BVBA und einmal mit bvba ?! Eins davon müsste wahrscheinlich gelöscht werden. Danke euch

**Comment by HakunaBanana** [comment]
@hannascholz  Danke für den Hinweis du hast Recht

**Comment by HakunaBanana** [comment]
@hannascholz ist gefixt und live. die branchen haben jetzt ebenfalls ne Nummer als Präfix
