### ISSUE TITLE
Dorset - Logo abgeschnitten

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#207]
Level 1: Logo ist am oberen Rand abgeschnitten.
Siehe Screenshot

![grafik](https://user-images.githubusercontent.com/72909142/97184526-4d5b4c80-179f-11eb-9d5e-d1893df2ee9b.png)

@HakunaBanana

**Comment by HakunaBanana** [comment]
fixed, war einen ticken zu weit von 16:9 entfernt
