### ISSUE TITLE
Medi - Video 

### ISSUE THREAD

**Issue by hannascholz** [HakunaBanana/otw-bug-tracker#208]
@HakunaBanana @Gizmo2106 Bitte noch 1 Video zusätzlich in der Deutschen Version einfügen. 
Folgendes Video muss  eingefügt werden: 

https://www.youtube.com/watch?v=nSzdxA4ibWU

 Das Video also zwischen Bild 8 und 9 einbauen 

 

Mit Bild 9 Endet die Produktwelt.

**Comment by HakunaBanana** [comment]
eingepflegt
