### ISSUE TITLE
Bauerfeind: Bilddatei tauschen

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#210]
Bitte das Bild auf der Partnerebene (sowohl im Eng als auch im DE) tauschen. Neue Bilder angehängt.
![bf_ot-world_dirk_EN_1920x1080_201027](https://user-images.githubusercontent.com/72909142/97338527-c59a3e80-1881-11eb-925a-879e5214042c.jpg)
![bf_ot-world_dirk_DE1920x1080_201027](https://user-images.githubusercontent.com/72909142/97338535-c92dc580-1881-11eb-9969-01b0e73780f7.jpg)

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  schicke dir dazu auch noch einmal eine Mail

**Comment by HakunaBanana** [comment]
@SchlSchleifnig Die Bilder sind aktualisiert. und live.
