### ISSUE TITLE
Falsche Ebene des Downloadfensters

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#215]
keine Prio, da es noch keiner gemerkt hat.

Bei Ausstellern mit sehr vielen Dateien im Downloadcenter wird dieses Fenster recht groß. Hierbei wird sichtbar, dass der obere Teil hinter die Flaggen rutscht.
Sieht nach der falschen Ebene aus.

![grafik](https://user-images.githubusercontent.com/72909142/97410203-0c7a4980-18ff-11eb-90de-1b93d66aaedc.png)

**Comment by HakunaBanana** [comment]
Ist live
