### ISSUE TITLE
YouTube Videos laufen nicht flüssig

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#216]
Das Bild der YouTube-Videos läuft sehr ruckelig.

Es wurden mehrere Waben von verschiedensten Rechnern ausprobiert.

@HakunaBanana

**Comment by HakunaBanana** [comment]
@SchlSchleifnig habt ihr die Tests alle aus dem Messe Leipzig Netz durchgeführt? Ich habe mir jetzt ~20minuten Videomaterial von Medi angeschaut und konnte das nicht feststellen. Ihr geht regulär über die Wabenwelt auf die Partner/Produkt-Level oder? GIbt es etwas worauf ich achten muss beim Abspielen? Also konkrete Momente wo man das Ruckeln merkt?

**Comment by HakunaBanana** [comment]
Grundlegend muss man sagen dass das Abspielen von Youtube Videos auf unserer Seite nicht von uns, sondern von Youtube selber durchgeführt wird. Wir übergeben die Id und Youtube regelt den Rest. Was noch auszuschliessen wäre, ist ein überlaufen des internen Browser Speichers, weil unity app und youtube video um die verfügbare Rechenleistung kämpfen. Das konnte ich aber bis jetzt nicht beobachten.

**Comment by SchlSchleifnig** [comment]
Wie besprochen beobachten wir diesen Issue erst einmal, da er nicht bei allen Testern aufgetaucht ist.
