### ISSUE TITLE
Button "Kommunikationstool"

### ISSUE THREAD

**Issue by hannascholz** [HakunaBanana/otw-bug-tracker#217]
@HakunaBanana 
Anscheinend lautet der Button "Kommunikationstool" bei einigen/allen Ausstellern "Kontaktformular".
Dies war jedoch ein spezieller Wunsch von Medi.
Bei allen anderen Ausstellern, sollte dieser Button jedoch "Kommunikationstool" oder auch gerne "Videokonferenz" oder auch "Live Chat" ( @SchlSchleifnig gerne Feedback zum Wording) heißen.

Bitte anpassen in Deutsch und ggfs. auch in Englisch.
Nur bei MEDI "Kontaktformular"

**Comment by SchlSchleifnig** [comment]
Ich wäre für Videokonferenz

**Comment by HakunaBanana** [comment]
ist live
