### ISSUE TITLE
Twikit

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#23]
Beschreibung
4 Bilder falsches Format
Youtube Link falsch

**Comment by Gizmo2106** [comment]
Zeilen Umbruch

**Comment by hannascholz** [comment]
Aussteller angescrhieben HS

**Comment by hannascholz** [comment]
Feedback von TWIKIT "I also noticed the uploading tool is still giving incorrect images with the product texts. " 
Bitte um Rückinfo @HakunaBanana  - man kann sich per REchtspfeil durch die fotos klicken, wenn man auf Foto 5 ist und mit dem links pfeil eins zurück will, springt der im Schnelldurchlauf zu Foto 1

**Comment by HakunaBanana** [comment]
ausgelagert nach #90
