### ISSUE TITLE
Intergrum

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#24]
Beschreibung
Logo auf der Wabe nicht lesbar

**Comment by hannascholz** [comment]
Aussteller angeschrieben HS

**Comment by usluga** [comment]
Webseite öffnet sich nicht

**Comment by SchlSchleifnig** [comment]
Webseite öffnet sich bei mir ohne Probleme. Bzgl. fehlender Daten wurde Kunde angeschrieben

**Comment by hannascholz** [comment]
Problem mit der Website nach wie vor
