### ISSUE TITLE
Vorum 

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#25]
Beschreibung
Fehlt 1 Foto

**Comment by hannascholz** [comment]
Aussteller angeschrieben HS

**Comment by HakunaBanana** [comment]
id: vorum-research

Kunde hat in de/en version noch unvollständigkeiten

**Comment by hannascholz** [comment]
Aussteller wurde informiert, ist Kanadier - Englische Inhalte sollen 1:1 ins Deutsche kopiert werden

**Comment by hannascholz** [comment]
VORUM:

"I know the deadline is past and I appreciate the extension you gave me. I realized I have one duplicate file under our downloadable files.
Under both our German and English version, there are two “Snider success stories” I would like to remove the first one and replace it with our product over view which I’ve attached to this email.
Is that something you’re able to do?" [
[Vorum Product Solution Overview.pdf](https://github.com/HakunaBanana/otw-bug-tracker/files/5400579/Vorum.Product.Solution.Overview.pdf)
](url)
@HakunaBanana @Gizmo2106  könnt ihr das noch einpflegen/ ändern? Seht ihr den Anhang? Das sieht irgendwie komisch aus.

**Comment by hannascholz** [comment]
E-mail sende ich euch hierzu nochmal speparat @HakunaBanana @Gizmo2106

**Comment by HakunaBanana** [comment]
eingepflegt
