### ISSUE TITLE
Youtube spielt nicht im Vollbild ab 

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#28]
Beschreibung

**Comment by SchlSchleifnig** [comment]
@HakunaBanana das ist für mich ein Bug.
Es geht um keinen bestimmten Aussteller!

**Comment by HakunaBanana** [comment]
@SchlSchleifnig völlig korrekt. Das ist im Moment extra deaktiviert. Werden wir aber dann entsprechend wieder aktivieren.

**Comment by HakunaBanana** [comment]
fixed

**Comment by HakunaBanana** [comment]
der Fix beinhaltet auch die bessere zugänglichkeit der Play/Pause und Volume Buttons
