### ISSUE TITLE
Fragezeichen - Fehlöffnung

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#29]
Wenn man das Fragezeichen (unten links) auswählt und zufällig dahinter eine Wabe liegt, öffnet sich die Wabe ebenfalls

**Comment by VicKraft** [comment]
Wenn man sich bereits im Fragezeichen Overlay befindet und statt auf das Haus in den leeren Hintergrundbereich klickt öffnet sich die dahinterliegende Wabe ebenfalls.

**Comment by HakunaBanana** [comment]
Duplikat, siehe #33
