### ISSUE TITLE
Sportlastic

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#30]
Beschreibung
2 mal drin

**Comment by hannascholz** [comment]
Aussteller angeschrieben HS

**Comment by HakunaBanana** [comment]
id: dartfish-deutschland

Kunde hat keine englischen Inhalt.
Kunde hat beim deutschen Inhalt:
Farbe nicht gesetzt
google maps url nicht gesetzt
social nicht gesetzt
