### ISSUE TITLE
360-Grad-Ansicht mit Maus - Nutzerhinweis

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#32]
Aus meiner Sicht wäre es hilfreich, wenn an dem "Fragezeichen" ein Mausower oder Ähnliches mit "Benutzerhilfe" stehen würde. Ich hatte Probleme bei der Bedienung mit der Maus, bis mir einfiel, dass die Hinweise zur Nutzung unter dem Fragezeichen liegen.

**Comment by TTroester** [comment]
Vielleicht sollten die Maushinweise als Startbild eingebettet werden?

**Comment by SchlSchleifnig** [comment]
Oder würdet ihr eine ganz andere Steuerung (z.B. Kamera geht automatisch immer mit der Maus mit, oder eher linke Maustaste anstatt der Rechten?) bevorzugen? @KNoellgen @TTroester

**Comment by TTroester** [comment]
Sofern es vorab die Erklärung für alle Nutzer relativ präsent gibt, finde ich es so schon okay. Man muss ja alle Aussteller schon erst einmal erfassen und bei einer automatische Mausfolge fällt die Auswahl und der Klick viel schwerer. Intuitiv hätte ich aber die Bewegung der Maus eher umgekehrt auf dem Display erwartet.

**Comment by SchlSchleifnig** [comment]
Erste Tester haben sich gemeldet, die dachten, dass es keine Steuerung gibt bzw. dass man sich nicht umschauen kann.

**Comment by janettguehlke** [comment]
Ich würde die Benutzungshinweise auch als Startbildschirm einblenden.
Ansonsten schließe ich mich Thomas an: ich hätte die Steuerung ähnlich wie bei Tablets/Handys auch genau anders herum erwartet.
Falls möglich, könnte die Navigation vielleicht zusätzlich mit der linken Maustaste (beim gedrückt halten) oder mit den Pfeiltasten erfolgen.
Ich musste beim ersten Öffnen auch etwas suchen bis ich die Steuerung entdeckt/verstanden habe ;-)

**Comment by SchlSchleifnig** [comment]
@SchlSchleifnig spricht noch einmal zu Steuerung mit Testern
