### ISSUE TITLE
Fragezeichen - BUG 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#33]
Beim Klick auf das Fragezeichen öffnet sich zusätzlich/über dem Fenster mit der Bedienhilfe ein BUG-Fenster der Produktwelt. 
-> siehe Screenshot 
![Bug_Fragezeichen](https://user-images.githubusercontent.com/72914177/96101399-b4425100-0ed5-11eb-991f-e95f67876e37.JPG)

**Comment by TTroester** [comment]
Beim Aussteller bzw. in der Produktwelt ist das Fragezeichen als Bestandteil der Startseite immer noch zu sehen aber nicht anklickbar. Vielleicht sollte es in jeder Ebene aufrufbar sein?
