### ISSUE TITLE
Designanmerkung Produktwelt

### ISSUE THREAD

**Issue by TTroester** [HakunaBanana/otw-bug-tracker#34]
- Sprachenflagge ev. als Wabe oder ohne Dot (sieht verzerrt/unstimmig aus)
- Textfeld Produktwelt sollte bündig zu anderer Linienführung sein oder dem Text entsprechend groß
- Text im Textfeld zu sehr an den Rand gequetscht, Rahmen etwas breiter
- Textfeld hat zu hohe Transparenz, wirkt teilweise zu unruhig vor den dahinter leigenden Wabenlogos / Text zu klein?!
![Produktwelt](https://user-images.githubusercontent.com/72913445/96101815-24e96d80-0ed6-11eb-81aa-058ab0342f8e.jpg)

**Comment by janettguehlke** [comment]
- die Flaggen in Wabenform ohne den Auswahlpunkt fände ich auch super
- Vielleicht könnte das Textfeld eine halbe Wabenform haben, damit es sich ins Layout einpasst?
- Ich fände es angenehmer, wenn die Startansicht im Hintergrund nicht oder nur ganz dezent erkennbar wäre. So lenkt es optisch für mich zu sehr vom Inhalt/Text ab.
- Falls möglich, wäre eine automatische Slideshow in geringer Geschwindigkeit für die einzelnen Produktblätter toll, damit jeder Besucher bemerkt, dass er noch weitere Inhalte entdecken kann.
- Die Wabe mit dem Zutritt in die Produktwelt bzw. zurück ins Hauptmenü würde ich blau oder grün beschriften, damit diese mehr auffällt. Falls möglich, fände ich auch eine ähnliche Darstellung wie die restlichen Icon-Waben unten cool.

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  wird bearbeitet
- Main --> wird zu Hauptmenü
- Linienführung
- Sprachflaggen mit Wabenhintergrund
- Position Textfeld
- Transparenz Textfeld

Nicht geändert wird:
- Slideshow, da explizit nicht gewünscht von Ausstellern

**Comment by HakunaBanana** [comment]
* Main --> wird zu Hauptmenü                  ->Done
* Linienführung                                           ->Done
* Sprachflaggen mit Wabenhintergrund     ->Done
* Position Textfeld                                       ->Done
* Transparenz Textfeld                                 ->Done
