### ISSUE TITLE
Main Menu Aussteller - Downloadwabe

### ISSUE THREAD

**Issue by TTroester** [HakunaBanana/otw-bug-tracker#35]
- Die Dateien im Download sollten nicht Datum oder Versionsangaben haben, sondern lediglich beschreiben um welchen Inhalt es sich handelt ( Negativbeispiel siehe bei Darthfish / Nowecor)  - Vielelicht findet man ein Wording über alle Aussteller (Ausstellername_Titel.pdf) Nach Veranstaltungsbesuch sollten sich die Fachbesucher in Ihrem Download-Dateiwust zurecht finden.

**Comment by SchlSchleifnig** [comment]
Der Aussteller bestimmt den Dateinamen. Hier haben wir keinen Einfluss.
Issue wird geschlossen.
