### ISSUE TITLE
Main Menu Aussteller / Standortlink

### ISSUE THREAD

**Issue by TTroester** [HakunaBanana/otw-bug-tracker#36]
Bei Mecuris läuft der Link zu einem Fehler

https://showroom-otw-connect.leipziger-messe.de/null

**Comment by TTroester** [comment]
Auch bei anderen Ausstellern ... Otto Bock....

**Comment by SchlSchleifnig** [comment]
geht bei mir ohne Probleme.
@HakunaBanana  kannst du bitte noch einmal testen

**Comment by HakunaBanana** [comment]
@SchlSchleifnig habe auch grade mal getestet. Ist alles in Ordnung.
der Kunde hat nen livestream eingebettet btw
