### ISSUE TITLE
Logofond

### ISSUE THREAD

**Issue by TTroester** [HakunaBanana/otw-bug-tracker#37]
Die Logos mit zwingend weißem Fond laut CD sollten auch eine komplett weiße Wabe bekommen. Vielleicht sollten dann auch alle Waben weiß sein und der 3D Effekt ergibt sich durch dunklere Seiten

**Comment by janettguehlke** [comment]
Ich würde auch einheitlich weiße Waben bevorzugen (sowohl in der Startansicht als auch oben links in den einzelnen Waben), da das für die meisten Logos vorteilhafter wäre und die Waben in der Startansicht alle die gleiche Gewichtung bekommen. Bei den hell erleuchteten finde ich aktuell, dass die Logos schwerer lesbar sind.

**Comment by HakunaBanana** [comment]
Durch neue App Version ist dieser Bug obsolet
