### ISSUE TITLE
Produktwelt OTOS

### ISSUE THREAD

**Issue by TTroester** [HakunaBanana/otw-bug-tracker#38]
Die Produkte mit den freigestellten Hintergründen wirken gegenüber anderer Aussteller sehr gut. Jedoch wird hier am stärksten deutlich, dass die verschiedenen Produktunterseiten nicht auf den ersten Blick gesehen werden . Auch die Pfeile zum weiter blättern sind relativ klein. Eine automatische Slideshow wäre doch auch optional ganz schick.

**Comment by SchlSchleifnig** [comment]
Funktion der automatischen Slideshow war drin, wurde aber explizit von den Ausstellern abgewählt.

@HakunaBanana  Pfeile sind hinter Text verschwunden.
Wird zum Bug. Scheint an der Auslösung zu liegen

**Comment by HakunaBanana** [comment]
Slider Pfeile stärker in den Vordergrund gehoben
