### ISSUE TITLE
Auswahl Wabe - Nutzerhinweis 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#39]
Bei Auswahl der Wabe bleibt der Pfeil ein Pfeil - Dadurch erkennt man nicht, dass man drauf klicken kann. 

Da es in der Wabe ein Hand-Mausover gibt, wäre es sehr benutzerfreundlich, wenn das auch bei der Wabenauswahl ginge. 

-> geringe Prio da Kleinigkeit

**Comment by SchlSchleifnig** [comment]
in Prüfung durch @HakunaBanana

**Comment by HakunaBanana** [comment]
Wabenhaptik jetzt angepasst
