### ISSUE TITLE
Confairmed

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#40]
- Produktwelt
-> Bei der dritten "Produktbeschreibung" ist am Textende ein Link vermerkt, der aber nicht verlinkt ist 
**-> Verlinkung in Produktbeschreibungen möglich?**

- Wabeneingang / Produktwelt
![Confairmed2](https://user-images.githubusercontent.com/72914177/96110920-d2fa1500-0ee0-11eb-91af-08e88562c4b6.JPG)
![Confairmend1](https://user-images.githubusercontent.com/72914177/96110923-d42b4200-0ee0-11eb-8e31-a2913e50cb9a.JPG)

-> BUG bei engl. Ansicht, siehe Screenshot 

- Icons
-> Verortung: Page not found 404

**Comment by SchlSchleifnig** [comment]
Verlinkung leider nicht möglich.
keinen Engl Content - dt. Content kopieren

**Comment by HakunaBanana** [comment]
@SchlSchleifnig @hannascholz könnt ihr hier nochmal nachfragen was genau mit Bug gemeint ist?

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  kann ich dir sogar ohne nachfragen sagen ;) 
Das ist das bekannte Problem, dass man Links, die in dem Textfeld sind, nicht direkt anklicken kann, sondern rauskopieren muss.
Das hatten wir ja aber bereits diskutiert und es ist aktuell leider nicht ändern.

Der Rest bezieht sich auf den fehlenden engl Inhalt - was dem Aussteller obligt

**Comment by HakunaBanana** [comment]
Danke für die schnelle Rückmeldung. Ich habe den Status entsprechend geändert.

id: confairmed-gmbh
Der Kunde hat noch keine Google Maps url gesetzt

**Comment by HakunaBanana** [comment]
@SchlSchleifnig @hannascholz ich habe den Status "für FN erledigt" wieder entfernt, da wir dem Kunden noch bescheid geben müssen. Oder habt ihr das schon getan? Dann setz ich den natürlicxh wieder.

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  danke für den Hinweis. Wir schreiben an.

**Comment by hannascholz** [comment]
@HakunaBanana @SchlSchleifnig Kunde wurde angeschrieben, kein Google Maps link gewünscht - Button/ Miniwabe soll entfernt werden
