### ISSUE TITLE
Thuasne - Kontaktwabe 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#41]
- Icons 
-> Mail-Verlinkung: Page not found 404

**Comment by usluga** [comment]
Kontaktformular nicht gefunden
Produktwelt baut sich sehr langsam auf

**Comment by SchlSchleifnig** [comment]
Mail-Verlinkung funktioniert bei mir einwandfrei. Eine neue Mail öffnet sich in meinem Mailprogramm.

@HakunaBanana  bitte testen und Feedback

**Comment by HakunaBanana** [comment]
@SchlSchleifnig da warst du schneller als ich.
Thuasne war der Kunde den Hanna eben meinte. Den habe ich grade angepasst.
