### ISSUE TITLE
Orthoscoot - Bug Logo / Verlinkungen

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#42]
- Wabe
-> Logo nicht vollständig zu erkennen, trotz eigentlich schwarzer Schrift 
![Orthoscoot](https://user-images.githubusercontent.com/72914177/96111616-b90d0200-0ee1-11eb-93a3-e1de34d54d71.JPG)

- Icons
-> Verortung: Page not found 404
-> Social, LinkedIn: Page not found 404

**Comment by usluga** [comment]
keine Verbindung zu anfahrtsplan

**Comment by HakunaBanana** [comment]
Kundendaten sind alle korrekt.  daher wird das Ticket geschlossen. Logo Bug wird unter #86 fortgeführt

**Comment by hannascholz** [comment]
Bitte logo einbauen, siehe E-mail gestern
