### ISSUE TITLE
Twikit - Bug Video 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#43]
- Video
-> kann nicht abgespielt werden
-> Fehlermeldung: Es ist ein Fehler aufgetreten. Bitte versuche es später noch einmal. (Wiedergabe-ID: MzzMl8FyLzI2L5oG)
Weitere Informationen: https://support.google.com/youtube/?p=player_error1&hl=de

- Sprache
-> dt. und engl. Beschreibung identisch

**Comment by usluga** [comment]
Video geht nicht

**Comment by HakunaBanana** [comment]
youtube affix falsch eingebenen. Keine Kommunikation notwendig.
