### ISSUE TITLE
Integrum - Bug Verlinkung 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#44]
- Icons
-> Link Website Page not found 404

**Comment by HakunaBanana** [comment]
Website war fehlerhaft eingegeben.

Kunde sollte darüber informiert werden das sein Zertifikat der Website abgelaufen ist.
Bei https://www.integrum.se zeigt Chrome eine "nicht vertrauenswürdig" meldung

**Comment by SchlSchleifnig** [comment]
wird angeschrieben

**Comment by hannascholz** [comment]
Integrum weiß Bescheid - Problem wird behoben

**Comment by hannascholz** [comment]
Problem besteht nach wie vor, Website kann nicht angezeigt werden
