### ISSUE TITLE
Wabe Spentys

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#45]
Beschreibung
Video geht nicht
Webseitenverlinkung geht nicht
Kontaktformular geht nicht
Produktwelt baut sich sehr langsam auf

**Comment by HakunaBanana** [comment]
id: spentys
Deutsche und Englische Version nur jeweils nur teilweise ausgefüllt.

**Comment by SchlSchleifnig** [comment]
Kunde wird angeschrieben

**Comment by hannascholz** [comment]
befüllt die Welt - erledigt
