### ISSUE TITLE
Wabe techmed3D

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#46]
Beschreibung
Produktvideos möchte eine Anmeldung bei youtube vor der Öffnung?

**Comment by KNoellgen** [comment]
> 
> 
> Beschreibung
> Produktvideos möchte eine Anmeldung bei youtube vor der Öffnung?

-> Beschreibung dt. = engl. 
-> Das mit dem Video war bei mir nicht.

**Comment by HakunaBanana** [comment]
Kunde hat vollständiges Profil. Keine Fehler
