### ISSUE TITLE
Wabe Nowecor AG

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#48]
Beschreibung
Webseite öffnet sich nicht 404 Not found
google maps öffnet sich nicht 404 not found

**Comment by HakunaBanana** [comment]
id: nowecor
Google Maps: Kunde hat Adresse eingegeben("Im Himmelreich 7, 49610 Quakenbrück")

und Website falsch geschrieben. Haben die Website jetzt angepasst. Bzgl. Google Maps link nochmal nachfragen am Besten.

**Comment by SchlSchleifnig** [comment]
Kunde wird angeschrieben

**Comment by hannascholz** [comment]
Kunde angeschrieben - evtl. Hilfe durch BM notwendig - Probleme mit Link

**Comment by HakunaBanana** [comment]
@hannascholz 
ich habe grade mal einen Link generiert: https://goo.gl/maps/pTHWx2RbBPqV4bW1A sollte auf die gewünschte Adresse zeigen.
Viele Grüße
