### ISSUE TITLE
Wabe Sporlastic

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#49]
Beschreibung

**Comment by usluga** [comment]
bei der Wabenweltansicht sehr weit am Bildrand
Video ohne Ton?

**Comment by KNoellgen** [comment]
**Das Video ist ohne Ton, habe es im Youtube ausprobiert.** 

zusätzlicher Hinweis: 
Icons sind sehr weit nach rechts gerutscht im Vgl. zu den anderen Waben

![Sporlastic](https://user-images.githubusercontent.com/72914177/96113613-b5c74580-0ee4-11eb-8b6d-33bb48d79340.JPG)

**Comment by KNoellgen** [comment]
> 
> 
> Beschreibung

engl. fehlt Beschreibung allg. + Produktbeschreibungen + Video funktioniert nicht (Es ist ein Fehler aufgetreten. Bitte versuche es später noch einmal. (Wiedergabe-ID: 8Nt3TwK6rq6xYCZg))

**Comment by HakunaBanana** [comment]
id: sporlastic

Youtube Video hat von Haus aus keinen Ton. Problem besteht nicht beim Youtube Player generell

**Comment by HakunaBanana** [comment]
Bug in #85 weitergeführt
