### ISSUE TITLE
Optadata

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#5]
Beschreibung
Wabe ist noch leer wird nicht geladen

**Comment by SchlSchleifnig** [comment]
Wabe funktioniert.

**Comment by hannascholz** [comment]
Bitte bei optadata Youtube link und Website Link austauschen @HakunaBanana @Gizmo2106 Danke euch
https://www.youtube.com/watch?v=MqHJmd8cb4M 
Affix: MqHJmd8cb4M
Website: https://www.optadata.de/live/
