### ISSUE TITLE
Ottobock - Bug Verlinkung / Product World 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#50]
- Icons
-> Verortung: Page not found 404

- Produktwelt engl.
-> Bilder werden nicht angezeigt 

![ottobock](https://user-images.githubusercontent.com/72914177/96113216-25890080-0ee4-11eb-8d81-167fa397e623.JPG)

**Comment by HakunaBanana** [comment]
DE: google maps url, Dateien nicht ausgefüllt
EN: Visitenkarte nicht ausgefüllt

**Comment by SchlSchleifnig** [comment]
wird in #6 weitergeführt
