### ISSUE TITLE
Wabe dorset

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#51]
Beschreibung
Keine Daten hinterlegt

**Comment by HakunaBanana** [comment]
Kunde hat fehlerhafte:
-Facebook(@dorset.ortho)
-Twitter(@dorset_ortho)
Urls hinterlegt.(z.B. https://www.facebook.com/BillGates/)

Youtube link ist playlist und kein video

**Comment by SchlSchleifnig** [comment]
Kunden hatte sich heute schon gemeldet - ist sowieso dran an den Punkten. Wird dennoch noch einmal angeschrieben.
