### ISSUE TITLE
Main Menu Antonius Köster

### ISSUE THREAD

**Issue by TTroester** [HakunaBanana/otw-bug-tracker#53]
Logo grau auf grau

**Comment by usluga** [comment]
im Englischen nichts hinterlegt?

**Comment by HakunaBanana** [comment]
englisch leer

**Comment by SchlSchleifnig** [comment]
Kunde wird angeschrieben

**Comment by SchlSchleifnig** [comment]
Kundin weiß Bescheid und ändert das Logo bis heute Abend.
