### ISSUE TITLE
Noventi - Inhalt engl. 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#55]
- Wabeneingang
-> keine engl. Beschreibung

- Produktwelt
-> keine engl. Beschreibung

- Video
-> engl. funktioniert nicht 
Es ist ein Fehler aufgetreten. Bitte versuche es später noch einmal. (Wiedergabe-ID: gOQsmq0hSoEXfL1O)

**Comment by hannascholz** [comment]
Aussteller bzgl. Inhalten angeschrieben HS

**Comment by HakunaBanana** [comment]
id: noventi
Kunde hat deutsche Version komplett ausgefüllt. englische Version leer

**Comment by SchlSchleifnig** [comment]
Aussteller wird keinen Englischen Content haben. In diesem Fall wird dt. Content einfach kopiert.
