### ISSUE TITLE
Optica - Inhalt engl. / Bug Verlinkungen 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#56]
- Wabeneingang
-> engl. Beschreibung fehlt 
-> Video auf engl. Seite nicht abzuspielen: 
Es ist ein Fehler aufgetreten. Bitte versuche es später noch einmal. (Wiedergabe-ID: gOQsmq0hSoEXfL1O) 

- Icons 
-> Videotool: Page not found 404
-> Downloads leer

- Produktwelt
-> engl. Beschreibungen fehlen

**Comment by hannascholz** [comment]
Aussteller zu den fehlenden Inhalten angeschrieben HS

**Comment by HakunaBanana** [comment]
id: optica-abrechnungszentrum

Kunde hat keine Dateien hochgeladen.

**Comment by SchlSchleifnig** [comment]
Aussteller hat keinen Englischen Content gepflegt. 
Dt Content wird kopiert @HakunaBanana
