### ISSUE TITLE
Verlag OT -  Bug Verlinkung

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#57]
- Wabeneingang
-> Video dt. funktioniert nicht 
Es ist ein Fehler aufgetreten. Bitte versuche es später noch einmal. (Wiedergabe-ID: gOQsmq0hSoEXfL1O) 

-> Beschreibung engl. fehlt
-> Video auf engl. Seite funktioniert nicht
Es ist ein Fehler aufgetreten. Bitte versuche es später noch einmal. (Wiedergabe-ID: gOQsmq0hSoEXfL1O) 

- Icons
-> Waben sehr weit nach recht gerutscht
![OT](https://user-images.githubusercontent.com/72914177/96115618-88c86200-0ee7-11eb-8fd7-4eda52da7fe2.JPG)

- Produktwelt 
-> Beschreibung engl. fehlt
-> Beschreibung dt. mit nicht identifizierbarem Sonderzeichen, siehe Screenshot
![OT2](https://user-images.githubusercontent.com/72914177/96115734-b4e3e300-0ee7-11eb-818b-c4846900f466.JPG)

**Comment by HakunaBanana** [comment]
id: verband-orthopaedie
Kunde hat noch kein youtube affix angegeben.
Englische Version leer

**Comment by SchlSchleifnig** [comment]
Deutschen Text auf Engl. Seite kopieren @HakunaBanana 

Bzgl YouTube-Affix schreiben wir an @hannascholz

**Comment by SchlSchleifnig** [comment]
Video miss durch Base Mesh gelöscht werden. Siehe LM cloud! @HakunaBanana
