### ISSUE TITLE
ACHTUNG: Sporlastic 2x angelegt

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#58]
Von Sporlastic befinden sich zwei Waben in der Welt.
-> 1x neben Ottobock
-> 1x unter medi
![sporlastic2](https://user-images.githubusercontent.com/72914177/96115969-0ab88b00-0ee8-11eb-81ad-2e94d0e26450.JPG)

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  wichtig!
