### ISSUE TITLE
Wabe BREG

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#59]
Beschreibung
es fehlen noch Angaben der Firma
Erklärtext ist auf deutsch und auf englisch in englisch

**Comment by HakunaBanana** [comment]
id: breg
Kundendaten in Deutsch und Englisch unvollständig(es fehlen Urls, in der Deutschen Version fehlt das Logo)

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  BREG ist ein amerikanischer Aussteler und kann keinen deutschen Inhalt liefern.
Englischen Content einfach in deutschen Bereich kopieren!
