### ISSUE TITLE
Anleitung Navigation als Pop-up beim 1. Betreten der Welt

### ISSUE THREAD

**Issue by lnoebel** [HakunaBanana/otw-bug-tracker#60]
Die Anleitung zur Steuerung mit der Maus sollte direkt erscheinen, wenn man die Welt das erste Mal betritt. Für mich war nicht ganz klar, wie ich mich in der Welt drehen kann. 
Auf die Idee, dann auf das Fragezeichen zu klicken kommt evtl. nicht jeder Nutzer bzw. weiß wahrscheinlich auch nicht jeder, dass man sich überhaupt in der Welt drehen kann.

**Comment by usluga** [comment]
Das finde ich auch. Die Anleitung wie man sich in der Welt bewegt, vielleicht ganz an den Anfang beim ersten Betreten

**Comment by SchlSchleifnig** [comment]
#79
