### ISSUE TITLE
Wabe DARTFISH

### ISSUE THREAD

**Issue by usluga** [HakunaBanana/otw-bug-tracker#61]
Beschreibung
Fotos in der Produktwelt fehlen?

**Comment by KNoellgen** [comment]
zusätzlicher Hinweis:

- Icons
-> Verortung: Page not found 404

**Comment by KNoellgen** [comment]
> 
> 
> Beschreibung
> Fotos in der Produktwelt fehlen?

Engl.: allg. Beschreibung und Produktbeschreibungen fehlen
Dt.: Fotos zu Produktbeschreibungen fehlen

**Comment by SchlSchleifnig** [comment]
Englischer Content bleibt wohl frei. Bzgl. Foto wird er angeschrieben

**Comment by SchlSchleifnig** [comment]
das eine Foto soll gelöscht werden! siehe Cloud!
4 weitere Youtube Links erforderlich! @HakunaBanana

**Comment by HakunaBanana** [comment]
produkt 5 wurde gelöscht

**Comment by hannascholz** [comment]
@HakunaBanana die 4 zusätzlichen Videos müssen ergänzt werden (siehe Cloud)

**Comment by hannascholz** [comment]
@HakunaBanana Bitte letztes Video löschen, sollten 4 Videos und 4 Bilder sein.

**Comment by Gizmo2106** [comment]
4 Videos sind drin
