### ISSUE TITLE
Sprachauswahl

### ISSUE THREAD

**Issue by SBeckerLE1** [HakunaBanana/otw-bug-tracker#62]
Wenn man in einer Wabe die Sprache "Englisch" auswählt, wird dies nicht gemerkt, wenn man aus der Wabe raus und in die nächste Wabe hineingeht. Idealerweise möchte ich die Sprachauswahl nur einmal treffen müssen.

**Comment by SchlSchleifnig** [comment]
@HakunaBanana wird umgesetzt.

**Comment by HakunaBanana** [comment]
ist umgesetzt
