### ISSUE TITLE
Suchfunktion Firma / Branche

### ISSUE THREAD

**Issue by SBeckerLE1** [HakunaBanana/otw-bug-tracker#65]
Suche nach Firmenname und Branche noch nicht in der Wabenwelt abgebildet.

**Comment by janettguehlke** [comment]
Das wäre super und zusätzlich noch ein interaktives Ausstellerverzeichnis mit alphabetischer Aufführung, wo man ebenfalls nach Branche/Firmenname filtern kann. Ist aber vermutlich eh an irgendeiner Stelle geplant :-)

**Comment by SBeckerLE1** [comment]
Ich sehe die Suchfunktion nach Firma ist nun da, toll. Könntet ihr die Liste bitte in alphabetischer Reihenfolge gestalten?

**Comment by SBeckerLE1** [comment]
Außerdem müsste der Text "Partner suchen" in deutsch und englisch sein.

![grafik](https://user-images.githubusercontent.com/72921516/96729044-06431500-13b5-11eb-92f6-51144cb73394.png)
