### ISSUE TITLE
Company Beschreibung Textfeld

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#67]
Kommentar Hr. Deumeland:
Text randbündig, so schwer lesbar, Fond, auf dem der Text steht, braucht Rand
![grafik](https://user-images.githubusercontent.com/72909142/96120867-7b16da80-0eef-11eb-9728-e71e9ec12ebc.png)

**Comment by SchlSchleifnig** [comment]
+ Text zu weit am Rand

**Comment by HakunaBanana** [comment]
fixed in Parter+Produkt Welt
