### ISSUE TITLE
Wabe "Product World" / "Main Menue"

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#68]
Kommentar Hr. Deumeland:
Hintergrundfarbe zu kräftig, bzw. "Menue" muss als wichtigste Wabe beim Kunden stärker leuchten

![grafik](https://user-images.githubusercontent.com/72909142/96121044-c8934780-0eef-11eb-9aba-8b8254f061fe.png)

**Comment by SchlSchleifnig** [comment]
@HakunaBanana  Wabenform + Wabendesign

**Comment by HakunaBanana** [comment]
Produktwelt/Hauptmenu button überarbeitet und mehr in den Vordergrund gehoben
