### ISSUE TITLE
Funktions-Icons

### ISSUE THREAD

**Issue by SchlSchleifnig** [HakunaBanana/otw-bug-tracker#69]
Anmerkung Herr Deumeland:
Icons zu gepresst links unten

![grafik](https://user-images.githubusercontent.com/72909142/96121265-1f991c80-0ef0-11eb-8c87-c016a56ba583.png)

**Comment by HakunaBanana** [comment]
Überprüfen von social menu

**Comment by HakunaBanana** [comment]
Duplikat, siehe #2
