### ISSUE TITLE
Antonius Köster

### ISSUE THREAD

**Issue by Gizmo2106** [HakunaBanana/otw-bug-tracker#7]
Beschreibung
Scrollen geht nur am rechten Rand vom Info Text
Falscher Link hinterlegt

https://innovative-cad-cam-solutions.de
Richtiger

**Comment by hannascholz** [comment]
@Gizmo2106: To do seitens Aussteller erforderlich?

**Comment by HakunaBanana** [comment]
Das man nur am rechten Rand des Infos Textes scrollen kann wird hier behandelt: #88

**Comment by HakunaBanana** [comment]
Der Kunde ist in Ordnung. Es gibt wohl ein redirect der url die gestern noch nicht aktiv war.
