### ISSUE TITLE
Optadata - Bug Verlinkungen / Inhalt engl. 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#71]
- Icons
-> Videotool: Page not found 404

- Wabeneingang
-> Beschreibung engl. leer
-> Video engl. funktioniert nicht

- Produktwelt
-> engl. kein Inhalt

**Comment by HakunaBanana** [comment]
id: optadata
Kunde hat englischen Inhalt nicht gepflegt. Extra oder versehen?

**Comment by SchlSchleifnig** [comment]
Opdatata hat keinen Englischen Content gepflegt. Muss er auch nicht. Geschlossen.
