### ISSUE TITLE
OTWorld Wabe Startseite

### ISSUE THREAD

**Issue by janettguehlke** [HakunaBanana/otw-bug-tracker#74]
Da würde ich mir wünschen, dass beim Klick vielleicht allgemeine Informationen erscheinen / die Webseite verlinkt ist / etc.

Außerdem sollte es eine Kontaktmöglichkeit zum OTW Team geben, also Vorstellung der einzelnen Teammitglieder mit (Video-)Chatmöglichkeit oder so.

**Comment by KNoellgen** [comment]
> 
> 
> Da würde ich mir wünschen, dass beim Klick vielleicht allgemeine Informationen erscheinen / die Webseite verlinkt ist / etc.
> 
> Außerdem sollte es eine Kontaktmöglichkeit zum OTW Team geben, also Vorstellung der einzelnen Teammitglieder mit (Video-)Chatmöglichkeit oder so.

Dem stimme ich zu! Es sollte (auch aus kommunikativer Sicht) eine OTWorld-Wabe geben, in der auf jeden Fall die Icons entsprechend verlinkt sind. (Website, Kontaktdaten, SoMe-Kanäle)

**Comment by SchlSchleifnig** [comment]
Es wird ein Aussteller "OTWorld" angelegt.
Projektteam/FN pflegt Wabe.

Nur 1 Ebene
- 1 x Company Beschreibung + Bild
- 1 x Icon Webseite
- 1 x Icon Visitenkarte
- 2 x Social Media Link

@HakunaBanana  bitte Zugangsdaten schicken
