### ISSUE TITLE
Streifeneder - Bug Verlinkung 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#76]
- Icons
-> Link zur Firmenwebsite: Page not found 404

**Comment by HakunaBanana** [comment]
Keine Interaktion notwendig. Kunde hatte fehlerhaften Websiten link.

**Comment by HakunaBanana** [comment]
Keine Interaktion notwendig. Kunde hatte fehlerhaften Websiten link. Wurde behoben
