### ISSUE TITLE
Icons auf Ausstellerebene - Verbesserungsvorschlag

### ISSUE THREAD

**Issue by FrankyJones72** [HakunaBanana/otw-bug-tracker#77]
Wenn ich einen Aussteller angeklickt habe, sehe ich unten die Icons für Kontakt, Google-Map, Download etc. Ich fände es besser, wenn der entsprechende Begriff kurz angezeigt würde, wenn sich der Mauszeiger über das Icon bewegt (in dem Moment habe ich ja noch nicht angeklickt!). Eigentlich ist es der Sinn von Icons, dass jeder sie intuitiv erkennen und verstehen sollte. Ich wusste es hier bei einigen nicht. Vielleicht geht es anderen ebenso...

**Comment by SchlSchleifnig** [comment]
Wird umgesetzt.

@HakunaBanana
