### ISSUE TITLE
Ortho Solid - Inhalte fehlen / Bug Verlinkungen 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#78]
- Wabeneingang
-> Firmenlogo fehlt 
-> Beschreibung dt. fehlt
-> Video dt. fehlt 

- Icons
-> Verortung: Page not found 404
-> Downloads leer
-> Link Firmenwebsite Page not found 404

- Produktwelt
-> Beschreibungen dt. leer

**Comment by HakunaBanana** [comment]
id: orthobroker-bvba

Kunde hat deutsches Profil nicht vollständig ausgefüllt. Entweder komplett leer lassen, oder komplett ausfüllen

**Comment by SchlSchleifnig** [comment]
Bekommt allgemeine Mail mit Hinweis, dass Teil-Inhalte aus ENG nicht nach DE kopiert werden.
