### ISSUE TITLE
Wabenkarussell ist möglich

### ISSUE THREAD

**Issue by FrankyJones72** [HakunaBanana/otw-bug-tracker#79]
Beschreibung
Es fehlt der deutliche Hinweis, dass man mit der rechten Maustaste die Wabenansicht drehen kann. Das ist ein spielerisches Element, das auch einen schönen Überblick über die teilnehmenden Unternehmen verschafft. Wenn es aber sehr viele Aussteller gibt, kann es sein, dass man die gar nicht auf den ersten Blick sieht. Das würde mir als bezahlender Aussteller nicht gefallen. Der Hinweis, wie man die Wabenauswahl verändert, ist auch aus diesem Grunde sehr wichtig.

**Comment by SchlSchleifnig** [comment]
wird berücksichtigt.
Erste Erklärung in Ladebildschirm (zusammen mit Logo und Welcome).

@HakunaBanana
