### ISSUE TITLE
Hintergrund auf Ebene des Ausstellers

### ISSUE THREAD

**Issue by FrankyJones72** [HakunaBanana/otw-bug-tracker#80]
Wenn ich einen Aussteller anklicke, also auf dessen Ebene komme, dann sehe ich den Hintergrund mit den Waben der anderen Aussteller sehr deutlich. Ich fände es besser, den Hintergrund "abzusoften", verschwommener darzustellen, wenn sowas geht. Momentan gucke ich mir da ein Produkt des Ausstellers X an, und gleich daneben sehe ich die Wabe mit dem Logo des Ausstellers Y.
Ich würde den Fond der aufgerufenen Logowabe (oben links), der Wabe "Betrete Produkt Welt" sowie das Textfeld zur Unternehmensbeschreibung in weiß wählen - nicht in hellgrau wie jetzt. Das tritt dann alles deutlicher hervor!

**Comment by SchlSchleifnig** [comment]
Hintergrund ist etwas angepasst
