### ISSUE TITLE
Aussteller Naked Prosthetics

### ISSUE THREAD

**Issue by FrankyJones72** [HakunaBanana/otw-bug-tracker#83]
Da gibt es offenbar keinen deutschen Text, nur englischen - ok, mag so sein. Dann würde ich oben bei der Länderkennung aber die englische Flagge "aktivieren". Außerdem fehlt ein Foto. Falls keins mehr kommt - wird dann der Platzhalter entfernt?

**Comment by HakunaBanana** [comment]
id: rcm-enterprises
Kunde hat vollständiges Profil
