### ISSUE TITLE
Produkt Slider checken

### ISSUE THREAD

**Issue by HakunaBanana** [HakunaBanana/otw-bug-tracker#90]
Beschreibung
Es existieren 2 Vorkommnisse wo der Produktslider:
* automatisch in der Diashow weiterspringt und Produkttext nicht geupdatet wird
* Die Betätigung der Pfeile nicht richtig den Produkttext aktualisiert

**Comment by HakunaBanana** [comment]
Ich habe den Productslider grade nochmal überprüft. Ich kann das Verhalten nciht reproduzieren. @hannascholz hast du es geschafft das Verhalten zu provozieren?

**Comment by hannascholz** [comment]
@HakunaBanana ? Bei Darco kann ich es nicht zu 100% bestätigen, bei Twikit kann ich es bestätigen. Diese Meldung hatten wir bereits nach dem ersten Durchlauf. "Langsames" Durchlaufen der Bilder durch klicken auf Rechtspfeil, wenn man auf dem letzten Foto angekommen ist und auf den Links pfeil (sprich eigentlich eins vor geht) springt er komplett auf Foto 1.

**Comment by SchlSchleifnig** [comment]
Fehler tritt nicht mehr auf
