### ISSUE TITLE
Welt dreht sich 

### ISSUE THREAD

**Issue by VicKraft** [HakunaBanana/otw-bug-tracker#93]
Aktuell dreht sich die Welt im Hintergrund weiter, auch wenn die Ausstellerseite geöffnet ist. Als User finde ich es eher unangenehm. Außerdem wird der Fokus von der Ausstellerseite abgelenkt, da man automatisch auf den Hintergrund mit achtet.

**Comment by KNoellgen** [comment]
Geht mir genauso. Auch die Auswahl einer Wabe wird erschwert, wenn sich die Welt dauerhaft dreht. 
-> Dadurch liest man auch die Anleitung für die Maus-Bedienung nicht. Ich war etwas irritiert :D 

Idee: Die Welt dreht sich 1-2x im Kreis, wenn man eintritt. Damit erkennt der Besucher, dass Bewegungen möglich sind und wird fortan nicht von der Drehbewegung "gestört".

**Comment by SchlSchleifnig** [comment]
Wird gestrichen, da schlechtes Tester-Feedback
