### ISSUE TITLE
Orthopädie.Technik Bundesinnungsverband - Wabe ungefüllt

### ISSUE THREAD

**Issue by VicKraft** [HakunaBanana/otw-bug-tracker#94]
In der deutschen Fassung ist die Produktseite leer. 
In der englischen Fassung werden die Formate mit angezeigt. 
![Orthopädie Technik_en](https://user-images.githubusercontent.com/72913883/96432160-c6d5c680-1204-11eb-83bb-e552a88e6e87.PNG)
![Orthopädie Technik_dt](https://user-images.githubusercontent.com/72913883/96432165-c89f8a00-1204-11eb-9be2-a73b4acf4f96.PNG)

**Comment by SchlSchleifnig** [comment]
Content wurde nur einsprachig gepflegt. vorhandener Content muss noch in die jeweilig andere Sprache kopiert werden.
To Do für BM @HakunaBanana
