### ISSUE TITLE
DJO Film nur in deutsch

### ISSUE THREAD

**Issue by FrankyJones72** [HakunaBanana/otw-bug-tracker#95]
Ist das so gewollt, dass DJO den Film nur auf der deutschen Seite zeigt, aber nicht auf der englischsprachigen? Ist zwar ein international tätiges Unternehmen, aber vielleicht haben sie den Film nicht in Englisch?

**Comment by SchlSchleifnig** [comment]
Dem Aussteller ist selber überlassen, in welchen Sprachen er welchen Content zeigt. Wir haben hier keinen Einfluss drauf
