### ISSUE TITLE
Bauerfeind auf Startbild eingeblendet - BUG

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#97]
Am unteren Rand der Wabenwelt wird beim Eintreten dauerhaft Bauerfeind eingeblendet. Dadurch sieht es aus, als wäre die Wabenwelt eine Bauerfeind-Veranstaltung ;) 
![Wabenwelt_gesamt](https://user-images.githubusercontent.com/72914177/96440585-7a8c8580-1208-11eb-8058-f46c7facfa77.JPG)

**Comment by VicKraft** [comment]
Wenn man auf den Schriftzug Bauerfeind klickt, wird man nicht automatisch auf die Wabe geleitet. Wenn sich eine andere Wabe durch Zufall gerade dahinter befindet wird dieser Aussteller geöffnet.

**Comment by SchlSchleifnig** [comment]
Das ist ein Platzhalter für verschiedene Werbebanner. Dieses wird zum nächsten Test final gefüllt werden.
