### ISSUE TITLE
Tageszeit der Welt stimmt nicht (Himmelfarbe) - BUG 

### ISSUE THREAD

**Issue by KNoellgen** [HakunaBanana/otw-bug-tracker#98]
Wenn ich mir recht erinnere, soll sich die Tageszeit in der Welt (Farbe des Himmels) an die jeweilige Zeit des Users anpassen. Bei mir ist es gerade 12.40 Uhr und die Welt zeigt einen Abendhimmel (oder früher Morgehimmel?) :)
![Wabenwelt_gesamt](https://user-images.githubusercontent.com/72914177/96440740-ad367e00-1208-11eb-92e0-a546f2c10d09.JPG)

**Comment by SchlSchleifnig** [comment]
@KNoellgen  wir haben uns ganztägig für romantische Abendstimmung entschieden... ;)
Tatsächlich mussten wir wegen der Lichtverhältnisse auf die Abendstunden gehen. Einige der Logos sind so schwach, dass sie den blauen Himmel mit Sonne leider nicht vertragen und dann nicht mehr erkannbar sind.
